app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    password_hash = db.Column(db.String(255))
    photos = db.relationship('PhotoProfile', backref='user', lazy="dynamic")

    article = db.relationship('Article', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User {self.username}'


class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer, primary_key=True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))


class Article(db.Model):
    __tablename__ = 'articles'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    post = db.Column(db.Text)
    posted = db.Column(db.Time, default=datetime.utcnow())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    def save_article(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_article(cls, id):
        article = Article.query.filter_by(id=id).all()
        return article

    @classmethod
    def delete_article(cls, id):
        article = Article.query.filter_by(id=id).first()
        db.session.delete(article)
        db.session.commit()


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    comment = db.Column(db.String(255))
    posted = db.Column(db.Time, default=datetime.utcnow())
    post_id = db.Column(db.Integer, db.ForeignKey('articles.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __repr__(self):
        return f'User (self.name)'

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls, id):
        comments = Comment.query.filter_by(post_id=id).all()
        return comments

    @classmethod
    def delete_comment(cls, id):
        comment = Comment.query.filter_by(id=id).first()
        db.session.delete(comment)
        db.session.commit()


class Quote:
    def __init__(self, id, author, quote, permalinlk):
        self.id = id
        self.author = author
        self.quote = quote
        self.permalinlk = permalinlk

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, ValidationError
from wtforms.validators import Required
from ..models import User


class ArticleForm(FlaskForm):
    title = StringField('Article title', validators=[Required()])
    post = TextAreaField('Article Post')
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    username = StringField('Your Name', validators=[Required()])
    comment = TextAreaField('Your Comment', validators=[Required()])
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

simple = SimpleMDE()

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos', IMAGES)
mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    # setting config
    # from .requests import configure_request
    # configure_request(app)

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from .forms import ArticleForm, CommentForm, UpdateProfile
from ..models import Article, User, PhotoProfile, Comment
from flask_login import login_required, current_user
from .. import db, photos


@main.route('/')
def index():
    post = Article.query.order_by(Article.posted.desc())
    # post = Article.get_article(id)
    title = f'Posts'
    return render_template('index.html', title=title, post=post)


@main.route('/post', methods=['GET', 'POST'])
@login_required
def post_form():
    form = ArticleForm()

    if form.validate_on_submit():
        title = form.title.data
        post = form.post.data

        new_post = Article(title=title, post=post, user=current_user)

        new_post.save_article()

        # mail_message("New Post",
        #              "email/new_article", user.email, post=new_post)

        return redirect(url_for('main.index'))

    title = f'New Post'
    return render_template('new_post.html', title=title, form=form)


@main.route('/post/<int:id>')
def post(id):
    post = Article.get_article(id)
    comments = Comment.get_comment(id)
    title = f'Article'
    return render_template('post.html', title=title, post=post, comments=comments)


@main.route('/post/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def deletepost(id):
    post = Article.delete_article(id)
    title = 'Delete Post'
    return redirect(url_for('main.index'))


@main.route('/post/comment/<int:id>', methods=['GET', 'POST'])
@login_required
def comment(id):
    comment_form = CommentForm()
    post = Article.get_article(id)

    if comment_form.validate_on_submit():
        new_comment = Comment(username=comment_form.username.data,
                              comment=comment_form.comment.data, post_id=id, user=current_user)
        new_comment.save_comment()
        return redirect(url_for('main.post', id=id))
        # return redirect(url_for('main.index'))

    title = f'Post Comment'
    comments = Comment.get_comment(id)
    return render_template('comment.html', title=title, comment_form=comment_form, post=post, comments=comments)


@main.route('/post/comments/<int:id>')
def post_comments(id):
    post = Article.get_article(id)
    comments = Comment.get_comment(id)
    title = f'Comments'
    render_template('post.html', comments=comments)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html", user=user)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Styles Block -->
{%block styles %}
{{super()}}
<!--Importing the simple mde css and js files  -->
{{ simplemde.css}}
{{ simplemde.js }}

<link rel="stylesheet" href="{{url_for('static', filename='css/bootswatch.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
<link href="https://fonts.googleapis.com/css?family=Noto+Sans+HK:100,400,500,700&display=swap" rel="stylesheet">
{% endblock %}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/comment.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      {{wtf.quick_form(comment_form)}}
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

<!-- Content Block -->
{% block content %}
<div class="container">
  <div class="row">
    {% if post %}
    {{macro.displayPost(post)}}
    {% else %}
    <h2><a href="{{url_for('main.post_form')}}">Post an Article</a></h2>
    {% endif %}
  </div>

  <div class="row">
    {% if quote %}
    {{macro.displayQuotes(quote)}}
    {% endif %}
  </div>
</div>
{% endblock %}

app/templates/macros.html
<!-- Displaying Posts -->
{% macro displayPost(posts) %}
{% for post in posts %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2 class="post-title"><a href="{{url_for('main.post', id=post.id)}}">{{post.title}}</a></h2>
      <p>{{post.post}}</p>
      <h4><a href="{{url_for('main.deletepost', id=post.id)}}">Delete Post</a></h4>
      <br>
      <hr><br>
    </div>
  </div>
</div>
{% endfor %}
{% endmacro %}

<!-- Displaying Comments -->
{% macro displayComment(comments) %}
{% for comment in comments %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <h4>{{comment.username}}</h4>
      <p>{{comment.comment}}</p>
    </div>
  </div>
</div>
{% endfor %}
{% endmacro %}

<!-- Dislay Quotes -->
{% macro displayQuotes(quotes_list) %}
{% for quote in quotes_list %}
<h3>{{quote.quote}}</h3>
<h5>{{quote.author}}</h5>
{% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03"
    aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item"><a class="nav-link" href="{{url_for('main.post_form')}}">Post an Article</a></li>
      {% if current_user.is_authenticated %}
      <li class="nav-item"><a class="nav-link"
          href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
      <li class="nav-item"><a class="nav-link" href="{{url_for('auth.logout')}}">Sign out</a></li>
      {% else %}
      <li class="nav-item"><a class="nav-link" href="{{url_for('auth.login')}}">Sign in</a></li>
      {%endif%}
    </ul>
  </div>
</nav>

app/templates/new_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
  <div class="col-md-8">
    {{ wtf.quick_form(form) }}
    {{simplemde.load}}
  </div>
</div>
{% endblock %}

app/templates/post.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}

<!-- Content Block -->
{% block content %}
<div class="container">
  <!-- Display Post -->
  <div class="row">
    {% if post %}
    {{macro.displayPost(post)}}
    {% endif %}
  </div>

  <!-- Display Comment -->
  <div class="">
    <!-- <h3>Leave a Comment</h3> -->
    <br>
    {% if comments %}
    <h5>This post has {{comments | count}} Comments</h5>
    {% for comment in comments %}
    <strong>
      <h5>{{comment.username}}</h5>
    </strong>
    <p>{{comment.comment}}</p>
    <hr>
    {% endfor %}
    {% endif %}
  </div>

</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h3> {{user.username| capitalize}} </h3>
      {% if user.bio %}
      <p> {{user.bio}}</p>
      {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
      {% endif %}
      {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
      {% endif %}
    </div>

    <div class="col-md-4">
      {% if user.profile_pic_path %}
      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}
      {% if user == current_user %}
      <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
        <input type="file" name="photo" class="form-control" required>
        <input type="submit">
        {% endif %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
{{wtf.quick_form(form)}}
{% endblock %}